CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id BIGSERIAL PRIMARY KEY,
    time DOUBLE PRECISION NOT NULL,
    v1 DOUBLE PRECISION NOT NULL,
    v2 DOUBLE PRECISION NOT NULL,
    v3 DOUBLE PRECISION NOT NULL,
    v4 DOUBLE PRECISION NOT NULL,
    v5 DOUBLE PRECISION NOT NULL,
    v6 DOUBLE PRECISION NOT NULL,
    v7 DOUBLE PRECISION NOT NULL,
    v8 DOUBLE PRECISION NOT NULL,
    v9 DOUBLE PRECISION NOT NULL,
    v10 DOUBLE PRECISION NOT NULL,
    v11 DOUBLE PRECISION NOT NULL,
    v12 DOUBLE PRECISION NOT NULL,
    v13 DOUBLE PRECISION NOT NULL,
    v14 DOUBLE PRECISION NOT NULL,
    v15 DOUBLE PRECISION NOT NULL,
    v16 DOUBLE PRECISION NOT NULL,
    v17 DOUBLE PRECISION NOT NULL,
    v18 DOUBLE PRECISION NOT NULL,
    v19 DOUBLE PRECISION NOT NULL,
    v20 DOUBLE PRECISION NOT NULL,
    v21 DOUBLE PRECISION NOT NULL,
    v22 DOUBLE PRECISION NOT NULL,
    v23 DOUBLE PRECISION NOT NULL,
    v24 DOUBLE PRECISION NOT NULL,
    v25 DOUBLE PRECISION NOT NULL,
    v26 DOUBLE PRECISION NOT NULL,
    v27 DOUBLE PRECISION NOT NULL,
    v28 DOUBLE PRECISION NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    class INTEGER NOT NULL CHECK (class IN (0, 1))
);

CREATE TABLE IF NOT EXISTS risk_scores (
    transaction_id BIGINT PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    score DOUBLE PRECISION NOT NULL CHECK (score >= 0 AND score <= 1),
    scored_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shap_values (
    transaction_id BIGINT PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    contributions JSONB NOT NULL,
    tier TEXT NOT NULL CHECK (tier IN ('auto-clear', 'ambiguous', 'auto-block')),
    conflict BOOLEAN NOT NULL,
    explained_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS case_embeddings (
    transaction_id BIGINT PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    embedding VECTOR(30) NOT NULL,
    embedded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS case_embeddings_embedding_idx
    ON case_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE TABLE IF NOT EXISTS investigation_memos (
    transaction_id BIGINT PRIMARY KEY REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    memo TEXT NOT NULL,
    model TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS investigation_chat (
    message_id BIGSERIAL PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
